//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.TripActivities = new HashSet<TripActivity>();
        }
    
        public int ActivityId { get; set; }
        public int CityId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public decimal EstimatedCost { get; set; }
        public decimal DurationHours { get; set; }
        public decimal Rating { get; set; }
        public bool IsTopPick { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual DestinationCity DestinationCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripActivity> TripActivities { get; set; }
    }
}
