//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GlobeTrotterDBEntities1 : DbContext
    {
        public GlobeTrotterDBEntities1()
            : base("name=GlobeTrotterDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategories { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DestinationCity> DestinationCities { get; set; }
        public virtual DbSet<SavedDestination> SavedDestinations { get; set; }
        public virtual DbSet<TripActivity> TripActivities { get; set; }
        public virtual DbSet<TripExpens> TripExpenses { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripStop> TripStops { get; set; }
        public virtual DbSet<vw_CityPopularityRankings> vw_CityPopularityRankings { get; set; }
        public virtual DbSet<vw_TripBudgetSummary> vw_TripBudgetSummary { get; set; }
    
        public virtual int sp_CloneTrip(Nullable<int> originalTripId, string newUserId, string newTripTitle, ObjectParameter newTripId)
        {
            var originalTripIdParameter = originalTripId.HasValue ?
                new ObjectParameter("OriginalTripId", originalTripId) :
                new ObjectParameter("OriginalTripId", typeof(int));
    
            var newUserIdParameter = newUserId != null ?
                new ObjectParameter("NewUserId", newUserId) :
                new ObjectParameter("NewUserId", typeof(string));
    
            var newTripTitleParameter = newTripTitle != null ?
                new ObjectParameter("NewTripTitle", newTripTitle) :
                new ObjectParameter("NewTripTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CloneTrip", originalTripIdParameter, newUserIdParameter, newTripTitleParameter, newTripId);
        }
    
        public virtual ObjectResult<sp_GetTripDailyTimeline_Result> sp_GetTripDailyTimeline(Nullable<int> tripId)
        {
            var tripIdParameter = tripId.HasValue ?
                new ObjectParameter("TripId", tripId) :
                new ObjectParameter("TripId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTripDailyTimeline_Result>("sp_GetTripDailyTimeline", tripIdParameter);
        }
    }
}
