//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripActivity
    {
        public int TripActivityId { get; set; }
        public int TripStopId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string CustomTitle { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public string TimeOfDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public decimal Cost { get; set; }
        public decimal DurationHours { get; set; }
        public int OrderIndex { get; set; }
        public string Notes { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual TripStop TripStop { get; set; }
    }
}
