//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripExpens
    {
        public int ExpenseId { get; set; }
        public int TripId { get; set; }
        public Nullable<int> TripStopId { get; set; }
        public string ExpenseCategory { get; set; }
        public string Title { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual TripStop TripStop { get; set; }
    }
}
