//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripStop()
        {
            this.TripActivities = new HashSet<TripActivity>();
            this.TripExpenses = new HashSet<TripExpens>();
        }
    
        public int TripStopId { get; set; }
        public int TripId { get; set; }
        public int CityId { get; set; }
        public int StopOrder { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public decimal AccommodationCost { get; set; }
        public string AccommodationDetails { get; set; }
        public decimal TransportCost { get; set; }
        public string TransportMode { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual DestinationCity DestinationCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripActivity> TripActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripExpens> TripExpenses { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
