//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CityPopularityRankings
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string CostIndex { get; set; }
        public decimal AvgDailyCost { get; set; }
        public string ImageUrl { get; set; }
        public decimal PopularityScore { get; set; }
        public Nullable<int> TimesPlannedInTrips { get; set; }
        public Nullable<int> WishlistCount { get; set; }
        public Nullable<int> AvailableActivitiesCount { get; set; }
    }
}
