//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TripBudgetSummary
    {
        public int TripId { get; set; }
        public string UserId { get; set; }
        public string TripTitle { get; set; }
        public decimal TotalBudget { get; set; }
        public string Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> TotalStops { get; set; }
        public decimal TotalStayCost { get; set; }
        public decimal TotalTransportCost { get; set; }
        public decimal TotalActivityCost { get; set; }
        public decimal TotalOtherExpenses { get; set; }
        public Nullable<decimal> GrandTotalEstimatedCost { get; set; }
        public Nullable<decimal> BudgetRemaining { get; set; }
        public int IsOverBudget { get; set; }
    }
}
